name: SNP-project

channels:
  - bioconda 
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - sra-tools
  - fastqc=0.11.9
  - multiqc=1.11
  - cutadapt
  - bwa
  - samtools
  - bcftools
  - vcftools
  - gffread
  - ncbi-datasets-cli
  - unzip